// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbsllkpjrgrbavgcvhde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNic2xsa3BqcmdyYmF2Z2N2aGRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MDY5NTUsImV4cCI6MjA3MzM4Mjk1NX0.a8N9hDjcHONaL60e61A_suk7mJyQVx0SffZJWbm7oJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});